volumes:
  pgdata:
  redisdata:
  mongodata:
  druiddata:

services:
  ##################################################
  # POSTGRES
  ##################################################
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-druid.sql:/docker-entrypoint-initdb.d/init-druid.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  ##################################################
  # AIRFLOW
  ##################################################
  airflow-webserver:
    image: lancelot-sang-louis-dataeng-airflow-webserver
    container_name: airflow-webserver
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW_UID: 1000
      AIRFLOW_API_AUTH_JWT_SECRET: 1e16daafb64b3f324ff52c23238bb73f
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow
    ports:
      - "8080:8080"

  airflow-scheduler:
    image: lancelot-sang-louis-dataeng-airflow-scheduler
    container_name: airflow-scheduler
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

  airflow-worker:
    image: lancelot-sang-louis-dataeng-airflow-worker
    container_name: airflow-worker
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

  airflow-triggerer:
    image: lancelot-sang-louis-dataeng-airflow-triggerer
    container_name: airflow-triggerer
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

  ##################################################
  # REDIS
  ##################################################
  redis:
    image: redis:7.2-bookworm
    container_name: redis
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: redispassword
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}

  ##################################################
  # MONGO
  ##################################################
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    ports:
      - "27017:27017"
      - "27018:27018"
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopassword
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - "8085:8081"

  ##################################################
  # PGADMIN
  ##################################################
  pgadmin:
    image: elestio/pgadmin
    container_name: pgadmin_airflow
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  ##################################################
  # DRUID
  ##################################################
  druid-coordinator:
    image: apache/druid:28.0.0
    container_name: druid-coordinator
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DRUID_XMS: 512M
      DRUID_XMX: 2G
      DRUID_METADATA_STORAGE_TYPE: postgresql
      DRUID_METADATA_STORAGE_CONNECTOR_CONNECTURI: jdbc:postgresql://postgres:5432/druid
      DRUID_METADATA_STORAGE_CONNECTOR_USER: druid
      DRUID_METADATA_STORAGE_CONNECTOR_PASSWORD: druid
      DRUID_EXTENSIONS_LOADLIST: ["postgresql-metadata-storage"]
    ports:
      - "8081:8081"
    volumes:
      - druiddata:/opt/druid/var

  druid-broker:
    image: apache/druid:28.0.0
    container_name: druid-broker
    depends_on:
      - druid-coordinator
    environment:
      DRUID_XMS: 512M
      DRUID_XMX: 2G
    ports:
      - "8082:8082"
    volumes:
      - druiddata:/opt/druid/var

  druid-historical:
    image: apache/druid:28.0.0
    container_name: druid-historical
    depends_on:
      - druid-coordinator
    environment:
      DRUID_XMS: 512M
      DRUID_XMX: 2G
    ports:
      - "8083:8083"
    volumes:
      - druiddata:/opt/druid/var

  druid-middlemanager:
    image: apache/druid:28.0.0
    container_name: druid-middlemanager
    depends_on:
      - druid-coordinator
    environment:
      DRUID_XMS: 512M
      DRUID_XMX: 2G
    ports:
      - "8091:8091"
    volumes:
      - druiddata:/opt/druid/var

  druid-router:
    image: apache/druid:28.0.0
    container_name: druid-router
    depends_on:
      - druid-coordinator
    environment:
      DRUID_XMS: 512M
      DRUID_XMX: 2G
    ports:
      - "8888:8888"
    volumes:
      - druiddata:/opt/druid/var

